config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

RedmineApp::Application.routes.draw do
  get 'semantic_search', to: 'semantic_search#index'

  get 'semantic_search/settings', to: 'semantic_search#settings'
  post 'semantic_search/settings', to: 'semantic_search#update_settings'

  post 'semantic_search/sync_embeddings', to: 'semantic_search#sync_embeddings'
end

app/models/issue_embedding.rb
class IssueEmbedding < ActiveRecord::Base
  belongs_to :issue

  # we can do this using neighbor gem (+ pgvector)
  has_neighbors :embedding_vector

  validates :issue, presence: true
  validates :embedding_vector, presence: true
  validates :content_hash, presence: true

  def self.calculate_content_hash(issue)
    content = [
      issue.subject,
      issue.description,
      issue.journals.map { |j| j.notes if j.notes.present? }.compact.join(" "),
      issue.time_entries.map { |te| te.comments if te.comments.present? }.compact.join(" ")
    ].join(" ")

    Digest::SHA256.hexdigest(content)
  end

  def needs_update?(issue)
    content_hash != self.class.calculate_content_hash(issue)
  end
end

app/controllers/semantic_search_controller.rb
class SemanticSearchController < ApplicationController
  before_action :require_login
  before_action :authorize_semantic_search
  before_action :require_admin, only: [:settings, :update_settings, :sync_embeddings]

  def index
    @projects = Project.visible.sorted.to_a
    @question = params[:q] || ""
    @results = []

    if @question.present?
      search_service = SemanticSearchService.new
      search_limit = Setting.plugin_semantic_search['search_limit'].to_i
      @results = search_service.search(@question, User.current, search_limit)
    end

    render layout: "base"
  rescue EmbeddingService::EmbeddingError => e
    flash.now[:error] = e.message
    render layout: "base"
  end

  def settings
    @settings = Setting.plugin_semantic_search
  end

  def update_settings
    Setting.plugin_semantic_search = params[:settings]
    flash[:notice] = l(:notice_successful_update)

    # check if model was changed, if yes, schedule a job to sync embeddings
    if params[:settings][:model] != Setting.plugin_semantic_search[:model]
      SyncEmbeddingsJob.perform_later
    end

    redirect_to action: "settings"
  end

  def sync_embeddings
    issue_count = Issue.count

    SyncEmbeddingsJob.perform_later

    flash[:notice] = l(:notice_sync_embeddings_started, count: issue_count)
    redirect_back(fallback_location: { controller: "issues", action: "index" })
  end

  private

  def authorize_semantic_search
    unless User.current.allowed_to?(:use_semantic_search, nil, global: true)
      deny_access
    end
  end
end

app/views/semantic_search/_issue_details.html.erb
<div class="search-result-issue">
  <dt class="issue-header">
    <div class="issue-title">
      <%= link_to "Issue ##{issue['issue_id']}: #{issue['subject']}",
                  issue_path(issue['issue_id']),
                  class: 'issue-link' %>
    </div>
    <div class="issue-meta">
      <span class="status <%= h(issue['status_name']).downcase.gsub(' ', '-') %>"><%= issue['status_name'] %></span>
      <% if issue['priority_name'].present? %>
        <span class="priority <%= h(issue['priority_name']).downcase.gsub(' ', '-') %>"><%= issue['priority_name'] %></span>
      <% end %>
    </div>
  </dt>
  <dd class="issue-body">
    <% if issue['description'].present? %>
      <div class="description">
        <%= textilizable(issue['description'], :object => Issue.find_by(id: issue['issue_id']), :headings => false) %>
      </div>
    <% end %>

    <div class="issue-footer">
      <p class="author">
        <%= authoring issue['created_on'], issue['author_name'] %>.
      </p>

      <div class="attributes">
        <% if issue['assigned_to_name'].present? %>
          <div class="attribute">
            <span class="label"><%= l(:field_assigned_to) %>:</span>
            <span class="value"><%= issue['assigned_to_name'] %></span>
          </div>
        <% end %>

        <% if issue['similarity_score'].present? %>
          <div class="attribute">
            <span class="label"><%= l(:label_similarity_score) %>:</span>
            <span class="value"><%= number_to_percentage(issue['similarity_score'] * 100, precision: 1) %></span>
          </div>
        <% end %>
      </div>
    </div>
  </dd>
</div>

app/views/semantic_search/_issues_sync_button.html.erb
<% if User.current.admin? %>
  <div class="contextual">
    <%= form_tag(semantic_search_sync_embeddings_path, method: :post, style: 'display: inline;') do %>
      <%= submit_tag l(:button_sync_embeddings), class: 'button icon icon-update' %>
    <% end %>
  </div>
<% end %>

app/views/semantic_search/_issues_sync_button_toolbar.html.erb
<% if User.current.admin? %>
  <div style="float: right; margin-right: 10px;">
    <%= form_tag(semantic_search_sync_embeddings_path, method: :post, style: 'display: inline-block;') do %>
      <%= submit_tag l(:button_sync_embeddings), class: 'button-positive' %>
    <% end %>
  </div>
<% end %>

app/views/semantic_search/index.html.erb
<%= stylesheet_link_tag 'semantic_search', plugin: 'semantic_search' %>

<div class="contextual">
  <% if User.current.admin? %>
    <%= link_to l(:label_settings), { controller: 'semantic_search', action: 'settings' }, class: 'icon icon-settings' %>
  <% end %>
</div>

<h2><%= l(:label_semantic_search) %></h2>

<%= form_tag({controller: 'semantic_search', action: 'index'}, method: :get, id: 'semantic-search-form') do %>
<div class="box search-form-box">
  <p>
    <%= label_tag "q", l(:label_semantic_search_query), class: 'search-form-label' %>
    <div class="search-input-group">
      <%= text_field_tag 'q', @question, size: 60, placeholder: l(:label_semantic_search_placeholder), autofocus: true, class: 'search-query-input' %>
      <%= submit_tag l(:button_search), name: nil, class: 'search-submit-button' %>
    </div>
  </p>

  <p class="note">
    <%= l(:text_semantic_search_info) %>
  </p>
</div>
<% end %>

<% if @question.present? %>
  <div id="search-results">
    <div class="search-results-count">
      <%= l(:label_result_count, count: @results.size) %>
    </div>

    <% if @results.present? %>
      <dl id="search-results-list" class="search-results">
        <% @results.each do |result| %>
          <% issue_id = result['issue_id'] %>
          <%# Render issue details here %>
          <%= render 'semantic_search/issue_details', issue: result %>
        <% end %>
      </dl>
    <% else %>
      <p class="nodata"><%= l(:label_no_data) %></p>
    <% end %>
  </div>
<% end %>

app/views/semantic_search/settings.html.erb
<h2><%= l(:label_semantic_search_settings) %></h2>

<%= form_tag({ controller: 'semantic_search', action: 'update_settings' }, method: :post) do %>
  <div class="box tabular settings">
    <p>
      <label><%= l(:label_openai_api_key) %></label>
      <em class="info"><%= l(:text_openai_api_key_info) %></em>
      <br>
      <code>OPENAI_API_KEY=<%= ENV['OPENAI_API_KEY'].present? ? "#{ENV['OPENAI_API_KEY'][0..5]}..." : l(:label_not_set) %></code>
      <br>
      <em class="info"><%= l(:text_env_variable_required) %></em>
    </p>

    <p>
      <label for="settings_base_url"><%= l(:label_base_url) %></label>
      <%= text_field_tag 'settings[base_url]', @settings['base_url'] || 'https://api.openai.com/v1', size: 50 %>
      <em class="info"><%= l(:text_base_url_info) %></em>
    </p>

    <p>
      <label for="settings_embedding_model"><%= l(:label_embedding_model) %></label>
      <%= select_tag 'settings[embedding_model]',
                     options_for_select([
                       ['text-embedding-ada-002 (Default)', 'text-embedding-ada-002'],
                       ['nomic-embed-text:latest (Ollama)', 'nomic-embed-text:latest']
                     ], @settings['embedding_model'] || 'text-embedding-ada-002') %>
    </p>

    <p>
      <label for="settings_search_limit"><%= l(:label_search_limit) %></label>
      <%= text_field_tag 'settings[search_limit]', @settings['search_limit'] || 25, size: 5 %>
      <em class="info"><%= l(:text_search_limit_info) %></em>
    </p>

    <p>
      <label for="settings_include_description"><%= l(:label_include_description) %></label>
      <%= check_box_tag 'settings[include_description]', '1', @settings['include_description'] != '0' %>
    </p>

    <p>
      <label for="settings_include_comments"><%= l(:label_include_comments) %></label>
      <%= check_box_tag 'settings[include_comments]', '1', @settings['include_comments'] != '0' %>
    </p>

    <p>
      <label for="settings_include_time_entries"><%= l(:label_include_time_entries) %></label>
      <%= check_box_tag 'settings[include_time_entries]', '1', @settings['include_time_entries'] != '0' %>
    </p>
  </div>

  <%= submit_tag l(:button_save) %>
<% end %>

app/views/settings/_semantic_search_settings.html.erb
<fieldset>
  <legend><%= l(:label_semantic_search_settings) %></legend>

  <div class="box tabular settings">
    <p>
      <label><%= l(:label_openai_api_key) %></label>
      <em class="info"><%= l(:text_openai_api_key_info) %></em>
      <br>
      <code>OPENAI_API_KEY=<%= ENV['OPENAI_API_KEY'].present? ? "#{ENV['OPENAI_API_KEY'][0..5]}..." : l(:label_not_set) %></code>
      <br>
      <em class="info"><%= l(:text_env_variable_required) %></em>
    </p>

    <p>
      <label for="settings_base_url"><%= l(:label_base_url) %></label>
      <%= text_field_tag 'settings[base_url]', settings['base_url'] || 'https://api.openai.com/v1', size: 50 %>
      <em class="info"><%= l(:text_base_url_info) %></em>
    </p>

    <p>
      <label for="settings_embedding_model"><%= l(:label_embedding_model) %></label>
      <%= select_tag 'settings[embedding_model]',
                     options_for_select([
                       ['text-embedding-ada-002 (Default)', 'text-embedding-ada-002'],
                       ['nomic-embed-text:latest (Ollama)', 'nomic-embed-text:latest']
                     ], settings['embedding_model'] || 'text-embedding-ada-002') %>
    </p>

    <p>
      <label for="settings_search_limit"><%= l(:label_search_limit) %></label>
      <%= text_field_tag 'settings[search_limit]', settings['search_limit'] || 25, size: 5 %>
      <em class="info"><%= l(:text_search_limit_info) %></em>
    </p>

    <p>
      <label for="settings_include_description"><%= l(:label_include_description) %></label>
      <%= check_box_tag 'settings[include_description]', '1', settings['include_description'] != '0' %>
    </p>

    <p>
      <label for="settings_include_comments"><%= l(:label_include_comments) %></label>
      <%= check_box_tag 'settings[include_comments]', '1', settings['include_comments'] != '0' %>
    </p>

    <p>
      <label for="settings_include_time_entries"><%= l(:label_include_time_entries) %></label>
      <%= check_box_tag 'settings[include_time_entries]', '1', settings['include_time_entries'] != '0' %>
    </p>
  </div>
</fieldset>